//NAO SE PODE COMEÇAR NOME DE VARIÁVEIS COM NÚMEROS("LET 2TESTE") MAS PODE TERMINAR ("LET TESTE2")

//OS ÚNICOS CARACTERES ESPECIAIS ACEITAVEIS SAO $ E _ (LET $NOME, _NOME)

//PODE SE INICIAR TANTO COM MINUSCULAS QUANTO MAIUSCULAS

//camelCase (let meuPrimeiroNome = "Pedro")


//para comentar use CTRL+K+C